spring.application.name=Ex1Biblioeca
spring.datasource.url=jdbc:postgresql://ep-mute-waterfall-an55mcuk-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_cDzfAJu6sdt5&sslmode=require&channelBinding=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_cDzfAJu6sdt5


# Console H2 para testes (opcional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


